default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 123
  host: localhost
  port: 5431
  database: xulifestyle-local-1

development:
  <<: *default
  database: xulifestyle-local-1

test:
  <<: *default
  database: xulifestyle-test

production:
  <<: *default
  database: xulifestyle-local-1
  username: postgres
  password: 123
